export const PERMISSIONS = {
  MENU_ADMIN: 'VER_MENU_ADMIN',
  AUDIT_GLOBAL: 'VER_AUDITORIA_GLOBAL',
  VIEW_PERMISSION_MAINTAINER: 'VER_MANTENEDOR_PERMISOS',
  UPDATE_PERMISSION_MAINTAINER: 'ACTUALIZAR_MANTENEDOR_PERMISOS',
  MANAGE_INTERFACES: 'MANTENEDOR_INTERFACES',
  MANAGE_SCREENS: 'MANTENEDOR_PANTALLAS',
  CREATE_USERS: 'CREAR_USUARIOS',
} as const;
